### ISSUE TITLE
Customizable border radii and border widths

### ISSUE THREAD

**Issue by johnotander** [tachyons-css/tachyons-generator#22]

**Comment by winkerVSbecks** [comment]
taking this one

**Comment by johnotander** [comment]
Awesome! I knocked out [border widths last night](https://github.com/tachyons-css/tachyons-generator/pull/38), but you can follow that pattern for the border radii ❤️. Also, this will likely be the pattern we follow for other customizable modules, so if you can think of improvements to this flow, let me know.
