### ISSUE TITLE
Dynamically add module css comment documentation

### ISSUE THREAD

**Issue by johnotander** [tachyons-css/tachyons-generator#33]

**Comment by winkerVSbecks** [comment]
Question about the docs for media queries. Currently this is what the tachyons src uses:

```
  Media Query Extensions:
    -ns = not-small
    -m  = medium
    -l  = large
```

The config only specifies the modifier and not a name.

```js
"customMedia": [
  { "m": 48 },
  { "l": 64 }
],
```

I could generate something like this:

```
  Media Query Extensions:
    -m  = 48em
    -l  = 64em
```

or we could change the config to use an object:

```js
"customMedia": {
  medium: { modifier: "m", value: 48 },
  large: { modifier: "l", value: 64 },
},
```

Or if you have any other ideas?

**Comment by johnotander** [comment]
I think the way you initially have it is great (`-l = 48em`). Down the road we can allow the ability to add names and such.
