### ISSUE TITLE
Name and define new colors?

### ISSUE THREAD

**Issue by ooloth** [tachyons-css/tachyons-generator#63]
So excited about this tool!

Any chance it will allow us to define colors not included in Tachyons by default? 

Some projects could really use a variable for brown, more shades of orange and gold, etc. and having the generator spread these colors throughout Tachyons (e.g. `.b--brown` or `.hover-bg-light-orange`) would be so helpful.

**Comment by johnotander** [comment]
It's not documented well yet (sorry 😬), but you can define your own colors that aren't in Tachyons.

Whatever your palette might be, you can define in the `"colors"` hash of the config, allowing you to introduce a larger _or_ smaller palette. One thing that's important to note is you need to define all colors you want in your palette if you override the defaults.

So, if you define brown and light orange to reference a color (even the same value), their classes will be generated. Though, currently `hover-bg-X` classes aren't being generated. I'll add that to my todo. I'll implement it either tonight or this weekend, will keep you posted.

**Comment by johnotander** [comment]
All color classes (including `hover-bg-X`) are now supported in `0.15.0`. You can modify the colors you want in your generated css with the [`colors`](https://github.com/tachyons-css/tachyons-generator#example-config) portion of the config.

Let us know if you have any other feature request, questions, or encounter any bugs 💟
