### ISSUE TITLE
breakpoint configuration

### ISSUE THREAD

**Issue by ctaepper** [tachyons-css/tachyons-generator#65]
currently, the logic generates breakpoints based on the following breakpoint
so it seems, that the breakpoint `ns` which is available in the regular tachyons cannot be produced

I want to mirror the material design breakpoints, which include not only `xs`, `sm`, `md`, `lg`, `xl`, but also `gt-xs`,` gt-sm`, `gt-md`, `gt-lg` (greater-than). They have the same semantic logic as tachyons' `ns`, basically only describing the `min-width`

as for the json config, this could be indicated with `<=` and/or `>=`
```json
  "customMedia": [
    { "sm": "600px" },
    { "md": "960px" },
    { "lg": "1280px" },
    { "xl": "1920px" },
    { "gt-xs": ">=600px" },
    { "gt-sm": ">=960px" },
    { "gt-md": ">=1280px" },
    { "gt-lg": ">=1920px" }
  ],
```
where `>=600px` would result in `screen and min-width(600px)`
I admit, this does not look nice, but thats only from the top of my head

**Comment by johnotander** [comment]
That's a great idea. I've gone ahead and spiked out an implementation (#66) that also adds further customization allowing you to pass an object instead of a media query value for further configurability:

```js
customMedia: [
     { "sm": "600px" },
    { "md": "960px" },
    { "lg": "1280px" },
    { "xl": "1920px" },
    { "gt-xs": { "value": "600px", "minWidth": true } },
    { "gt-sm":  { "value": "960px", "minWidth": true }  },
    { "gt-md":  { "value": "1280px", "minWidth": true }  },
    { "gt-lg":  { "value": "1920px", "minWidth": true, "prefix": true, "delimiter": "@" }  }
]
```

The last mq options make the class naming become `db@gt-lg` for that breakpoint : )

**Comment by ctaepper** [comment]
while you're at it, you could also add maxWidth

**Comment by johnotander** [comment]
Done < 3

**Comment by ctaepper** [comment]
@johnotander works great! 

except one thing:
```json
  "customMedia": [
    { "xl": "1920px" },
    { "gt-lg": {"value": "1920px", "minWidth": true }}
  ],
```
the 2nd breakpoint doesn't get generated. i haven't looked into the code, but I assume it has something todo with both resulting in `screen and (min-width: 1920px)`

I am aware that it doesn't really make sense to have 2 identical breakpoints... the semantic meaning though is different. bottom line: I'm unsure if this is a bug or a feature

**Comment by johnotander** [comment]
I'll look into it to see what's going on today. Definitely think its a bug since they're named differently.

**Comment by johnotander** [comment]
Hey @ctaepper,

Just ran the generator with the `xl` and `gt-lg` media queries and they both seem to be generated for me. Are you sure the second isn't being generated?

**Comment by ctaepper** [comment]
I'm sorry, I have more breakpoints and I didn't realize, that the 2 breakpoints got merged together within one single media query

**Comment by johnotander** [comment]
No worries, glad it works! 😸
